/* ============================================================
   Logic for the Fun tools: randomizer, crate sim, backpack.
   Relies on main.js (el, wikiUrl, itemChip, loadoutCard, classSlug)
   and funpools.js (WEAPONS, COSMETICS, CRATE_*, QUALITY_COLORS, BACKPACK).
   ============================================================ */

function pick(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}
function pickN(arr, n) {
  const copy = arr.slice();
  const out = [];
  while (out.length < n && copy.length) {
    out.push(copy.splice(Math.floor(Math.random() * copy.length), 1)[0]);
  }
  return out;
}

/* ---------- Loadout Randomizer ---------- */
const RANDOM_BLURBS = [
  "Generated by pure chaos.", "No thoughts, just this.", "The algorithm has spoken.",
  "Statistically, a war crime.", "Somebody's gotta run it.", "Peak performance, probably.",
  "Don't question the dice.", "Certified cursed."
];

function renderRandomizer() {
  const out = document.getElementById("randomizer-output");
  const btn = document.getElementById("reroll-btn");
  if (!out || !btn) return;

  function roll() {
    const cls = pick(Object.keys(WEAPONS));
    const w = WEAPONS[cls];
    const items = [pick(w.primary), pick(w.secondary), pick(w.melee)]
      .concat(pickN(COSMETICS, 2));
    const lo = {
      name: "Random " + cls,
      class: cls,
      image: "",
      blurb: pick(RANDOM_BLURBS),
      items: items,
      notes: "Hit Reroll for another disaster."
    };
    out.innerHTML = "";
    out.appendChild(loadoutCard(lo));
  }

  btn.addEventListener("click", roll);
  roll();
}

/* ---------- Crate Opening Simulator ---------- */
function rollGrade() {
  const total = CRATE_GRADES.reduce((s, g) => s + g.weight, 0);
  let r = Math.random() * total;
  for (const g of CRATE_GRADES) {
    if ((r -= g.weight) <= 0) return g;
  }
  return CRATE_GRADES[0];
}

function renderCrate() {
  const stage = document.getElementById("crate-stage");
  const btn = document.getElementById("open-btn");
  const result = document.getElementById("crate-result");
  const histEl = document.getElementById("crate-history");
  if (!stage || !btn) return;

  const history = [];
  let rolling = false;

  function open() {
    if (rolling) return;
    rolling = true;
    btn.disabled = true;
    result.className = "crate-result";
    stage.classList.add("shaking");

    // spin through random names, then settle
    let ticks = 0;
    const spin = setInterval(function () {
      result.innerHTML = "<span class='spin-name'>" + pick(CRATE_ITEMS) + "</span>";
      if (++ticks > 16) {
        clearInterval(spin);
        settle();
      }
    }, 60);

    function settle() {
      stage.classList.remove("shaking");
      const unusual = Math.random() < UNUSUAL_CHANCE;
      const grade = unusual ? { name: "★ Unusual ★", color: "#8650ac" } : rollGrade();
      const item = pick(CRATE_ITEMS);

      result.innerHTML = "";
      result.style.setProperty("--grade", grade.color);
      result.classList.add("revealed");
      if (unusual) result.classList.add("jackpot");

      const gradeTag = el("div", "grade-tag", grade.name);
      gradeTag.style.color = grade.color;
      const a = document.createElement("a");
      a.className = "crate-item-name";
      a.href = wikiUrl(item);
      a.target = "_blank";
      a.rel = "noopener noreferrer";
      a.textContent = item;
      a.style.color = grade.color;
      result.appendChild(gradeTag);
      result.appendChild(a);
      if (unusual) {
        result.appendChild(el("div", "unusual-effect", "Effect: " + pick(UNUSUAL_EFFECTS)));
      }

      history.unshift({ item: item, grade: grade.name, color: grade.color });
      drawHistory();
      rolling = false;
      btn.disabled = false;
    }
  }

  function drawHistory() {
    if (!histEl) return;
    histEl.innerHTML = "<h3>Recent unboxes</h3>";
    const ul = el("ul", "history-list");
    history.slice(0, 10).forEach(function (h) {
      const li = el("li");
      const dot = el("span", "history-dot");
      dot.style.background = h.color;
      li.appendChild(dot);
      li.appendChild(document.createTextNode(h.item + " — " + h.grade));
      ul.appendChild(li);
    });
    histEl.appendChild(ul);
  }

  btn.addEventListener("click", open);
}

/* ---------- Backpack Showcase ---------- */
// rarity order (rarest first) for sorting + filter buttons
const QUALITY_RANK = ["Unusual", "Collector's", "Genuine", "Strange", "Haunted",
  "Vintage", "Decorated Weapon", "Unique", "Normal"];
const ICON_BASE = "https://community.cloudflare.steamstatic.com/economy/image/";

function renderBackpack() {
  const grid = document.getElementById("backpack-grid");
  if (!grid) return;
  const live = (typeof STEAM_WORKER_URL !== "undefined" && STEAM_WORKER_URL && typeof STEAM_ID !== "undefined" && STEAM_ID);
  if (live) {
    grid.innerHTML = "<p class='empty'>Loading inventory from Steam…</p>";
    renderLiveBackpack(grid).catch(function (e) {
      grid.innerHTML = "<p class='empty err'>Couldn't load live inventory (" + e.message + "). Showing curated list.</p>";
      const wrap = el("div", "backpack-grid");
      grid.appendChild(wrap);
      renderCuratedBackpack(wrap);
    });
  } else {
    renderCuratedBackpack(grid);
  }
}

async function renderLiveBackpack(grid) {
  const res = await fetch(STEAM_WORKER_URL + "?steamid=" + encodeURIComponent(STEAM_ID), { cache: "no-store" });
  const data = await res.json();
  if (data.error) throw new Error(data.error);
  if (!data.descriptions || !data.assets) throw new Error("no inventory data");

  // count duplicates per item class
  const counts = {};
  data.assets.forEach(function (a) {
    var k = a.classid + "_" + a.instanceid;
    counts[k] = (counts[k] || 0) + 1;
  });

  const items = data.descriptions.map(function (d) {
    var quality = "Unique";
    (d.tags || []).forEach(function (t) { if (t.category === "Quality") quality = t.localized_tag_name; });
    return {
      name: d.market_name || d.name,
      color: "#" + (d.name_color || "7d6d00"),
      quality: quality,
      count: counts[d.classid + "_" + d.instanceid] || 1,
      icon: d.icon_url_large || d.icon_url,
      market: d.marketable ? d.market_hash_name : null
    };
  });

  const rank = function (q) { var i = QUALITY_RANK.indexOf(q); return i < 0 ? 99 : i; };
  items.sort(function (a, b) { return rank(a.quality) - rank(b.quality) || a.name.localeCompare(b.name); });

  // build filter bar (All + each quality present, rarest first)
  const present = QUALITY_RANK.filter(function (q) { return items.some(function (it) { return it.quality === q; }); });
  const host = grid.parentNode;
  const filterBar = el("div", "class-filter bp-filter");
  host.insertBefore(filterBar, grid);

  function draw(q) {
    grid.innerHTML = "";
    var list = q === "All" ? items : items.filter(function (it) { return it.quality === q; });
    grid.appendChild(buildCount(list.length, items.length));
    var tiles = el("div", "bp-tiles");
    list.forEach(function (it) { tiles.appendChild(bpTile(it)); });
    grid.appendChild(tiles);
  }

  ["All"].concat(present).forEach(function (q, i) {
    var b = el("button", "filter-btn" + (i === 0 ? " active" : ""), q);
    if (q !== "All") b.style.setProperty("--accent", QUALITY_COLORS[q] || "#b2b2b2");
    b.addEventListener("click", function () {
      filterBar.querySelectorAll(".filter-btn").forEach(function (x) { x.classList.remove("active"); });
      b.classList.add("active");
      draw(q);
    });
    filterBar.appendChild(b);
  });

  draw("All");
}

function buildCount(shown, total) {
  return el("p", "bp-count-line", "Showing <strong>" + shown + "</strong> of " + total + " items.");
}

function bpTile(it) {
  var tag = it.market ? document.createElement("a") : document.createElement("div");
  tag.className = "bp-tile";
  tag.style.setProperty("--q", it.color);
  tag.title = it.name + (it.count > 1 ? " (x" + it.count + ")" : "");
  if (it.market) {
    tag.href = "https://steamcommunity.com/market/listings/440/" + encodeURIComponent(it.market);
    tag.target = "_blank";
    tag.rel = "noopener noreferrer";
  }
  if (it.icon) {
    var img = document.createElement("img");
    img.src = ICON_BASE + it.icon + "/96fx96f";
    img.alt = it.name;
    img.loading = "lazy";
    tag.appendChild(img);
  }
  if (it.count > 1) tag.appendChild(el("span", "bp-tile-count", "x" + it.count));
  tag.appendChild(el("span", "bp-tile-name", it.name));
  return tag;
}

function renderCuratedBackpack(grid) {
  if (typeof BACKPACK === "undefined" || !BACKPACK.length) {
    grid.appendChild(el("p", "empty", "No items yet. Add some in js/funpools.js."));
    return;
  }
  BACKPACK.forEach(function (it) {
    const color = (QUALITY_COLORS[it.quality]) || "#b2b2b2";
    const card = el("div", "bp-card");
    card.style.setProperty("--q", color);
    card.appendChild(el("div", "bp-quality", it.quality || "Normal"));
    const a = document.createElement("a");
    a.className = "bp-name";
    a.href = wikiUrl(it.wiki || it.name);
    a.target = "_blank";
    a.rel = "noopener noreferrer";
    a.textContent = it.name;
    card.appendChild(a);
    if (it.effect) card.appendChild(el("div", "bp-effect", "✦ " + it.effect));
    if (it.value) card.appendChild(el("div", "bp-value", it.value));
    if (it.note) card.appendChild(el("div", "bp-note", it.note));
    grid.appendChild(card);
  });
}
