/* ============================================================
   Logic for the Fun tools: randomizer, crate sim, backpack.
   Relies on main.js (el, wikiUrl, itemChip, loadoutCard, classSlug)
   and funpools.js (WEAPONS, COSMETICS, CRATE_*, QUALITY_COLORS, BACKPACK).
   ============================================================ */

function pick(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}
function pickN(arr, n) {
  const copy = arr.slice();
  const out = [];
  while (out.length < n && copy.length) {
    out.push(copy.splice(Math.floor(Math.random() * copy.length), 1)[0]);
  }
  return out;
}

/* ---------- Loadout Randomizer ---------- */
const RANDOM_BLURBS = [
  "Generated by pure chaos.", "No thoughts, just this.", "The algorithm has spoken.",
  "Statistically, a war crime.", "Somebody's gotta run it.", "Peak performance, probably.",
  "Don't question the dice.", "Certified cursed."
];

function renderRandomizer() {
  const out = document.getElementById("randomizer-output");
  const btn = document.getElementById("reroll-btn");
  if (!out || !btn) return;

  function roll() {
    const cls = pick(Object.keys(WEAPONS));
    const w = WEAPONS[cls];
    const items = [pick(w.primary), pick(w.secondary), pick(w.melee)]
      .concat(pickN(COSMETICS, 2));
    const lo = {
      name: "Random " + cls,
      class: cls,
      image: "",
      blurb: pick(RANDOM_BLURBS),
      items: items,
      notes: "Hit Reroll for another disaster."
    };
    out.innerHTML = "";
    out.appendChild(loadoutCard(lo));
  }

  btn.addEventListener("click", roll);
  roll();
}

/* ---------- Crate Opening Simulator ---------- */
function rollGrade() {
  const total = CRATE_GRADES.reduce((s, g) => s + g.weight, 0);
  let r = Math.random() * total;
  for (const g of CRATE_GRADES) {
    if ((r -= g.weight) <= 0) return g;
  }
  return CRATE_GRADES[0];
}

function renderCrate() {
  const stage = document.getElementById("crate-stage");
  const btn = document.getElementById("open-btn");
  const result = document.getElementById("crate-result");
  const histEl = document.getElementById("crate-history");
  if (!stage || !btn) return;

  const history = [];
  let rolling = false;

  function open() {
    if (rolling) return;
    rolling = true;
    btn.disabled = true;
    result.className = "crate-result";
    stage.classList.add("shaking");

    // spin through random names, then settle
    let ticks = 0;
    const spin = setInterval(function () {
      result.innerHTML = "<span class='spin-name'>" + pick(CRATE_ITEMS) + "</span>";
      if (++ticks > 16) {
        clearInterval(spin);
        settle();
      }
    }, 60);

    function settle() {
      stage.classList.remove("shaking");
      const unusual = Math.random() < UNUSUAL_CHANCE;
      const grade = unusual ? { name: "★ Unusual ★", color: "#8650ac" } : rollGrade();
      const item = pick(CRATE_ITEMS);
      if (window.SFX) SFX.unbox(unusual ? 3 : CRATE_GRADES.indexOf(grade));

      result.innerHTML = "";
      result.style.setProperty("--grade", grade.color);
      result.classList.add("revealed");
      if (unusual) result.classList.add("jackpot");

      const gradeTag = el("div", "grade-tag", grade.name);
      gradeTag.style.color = grade.color;
      const a = document.createElement("a");
      a.className = "crate-item-name";
      a.href = wikiUrl(item);
      a.target = "_blank";
      a.rel = "noopener noreferrer";
      a.textContent = item;
      a.style.color = grade.color;
      result.appendChild(gradeTag);
      result.appendChild(a);
      if (unusual) {
        result.appendChild(el("div", "unusual-effect", "Effect: " + pick(UNUSUAL_EFFECTS)));
      }

      history.unshift({ item: item, grade: grade.name, color: grade.color });
      drawHistory();
      rolling = false;
      btn.disabled = false;
    }
  }

  function drawHistory() {
    if (!histEl) return;
    histEl.innerHTML = "<h3>Recent unboxes</h3>";
    const ul = el("ul", "history-list");
    history.slice(0, 10).forEach(function (h) {
      const li = el("li");
      const dot = el("span", "history-dot");
      dot.style.background = h.color;
      li.appendChild(dot);
      li.appendChild(document.createTextNode(h.item + " — " + h.grade));
      ul.appendChild(li);
    });
    histEl.appendChild(ul);
  }

  btn.addEventListener("click", open);
}

/* ---------- Backpack Showcase ---------- */
// rarity order (rarest first) for sorting + filter buttons
const QUALITY_RANK = ["Unusual", "Collector's", "Genuine", "Strange", "Haunted",
  "Vintage", "Decorated Weapon", "Unique", "Normal"];
const ICON_BASE = "https://community.cloudflare.steamstatic.com/economy/image/";

function renderBackpack() {
  const grid = document.getElementById("backpack-grid");
  if (!grid) return;
  const live = (typeof STEAM_WORKER_URL !== "undefined" && STEAM_WORKER_URL && typeof STEAM_ID !== "undefined" && STEAM_ID);
  if (live) {
    grid.innerHTML = "<p class='empty'>Loading inventory from Steam…</p>";
    renderLiveBackpack(grid).catch(function (e) {
      grid.innerHTML = "<p class='empty err'>Couldn't load live inventory (" + e.message + "). Showing curated list.</p>";
      const wrap = el("div", "backpack-grid");
      grid.appendChild(wrap);
      renderCuratedBackpack(wrap);
    });
  } else {
    renderCuratedBackpack(grid);
  }
}

async function renderLiveBackpack(grid) {
  const res = await fetch(STEAM_WORKER_URL + "?steamid=" + encodeURIComponent(STEAM_ID), { cache: "no-store" });
  const data = await res.json();
  if (data.error) throw new Error(data.error);
  if (!data.descriptions || !data.assets) throw new Error("no inventory data");

  // count duplicates per item class
  const counts = {};
  data.assets.forEach(function (a) {
    var k = a.classid + "_" + a.instanceid;
    counts[k] = (counts[k] || 0) + 1;
  });

  const items = data.descriptions.map(function (d) {
    var quality = "Unique";
    (d.tags || []).forEach(function (t) { if (t.category === "Quality") quality = t.localized_tag_name; });
    return {
      name: d.market_name || d.name,
      color: "#" + (d.name_color || "7d6d00"),
      quality: quality,
      count: counts[d.classid + "_" + d.instanceid] || 1,
      icon: d.icon_url_large || d.icon_url,
      market: d.marketable ? d.market_hash_name : null
    };
  });

  const rank = function (q) { var i = QUALITY_RANK.indexOf(q); return i < 0 ? 99 : i; };
  items.sort(function (a, b) { return rank(a.quality) - rank(b.quality) || a.name.localeCompare(b.name); });

  // build filter bar (All + each quality present, rarest first)
  const present = QUALITY_RANK.filter(function (q) { return items.some(function (it) { return it.quality === q; }); });
  const host = grid.parentNode;
  const filterBar = el("div", "class-filter bp-filter");
  host.insertBefore(filterBar, grid);

  function draw(q) {
    grid.innerHTML = "";
    var list = q === "All" ? items : items.filter(function (it) { return it.quality === q; });
    grid.appendChild(buildCount(list.length, items.length));
    var tiles = el("div", "bp-tiles");
    list.forEach(function (it) { tiles.appendChild(bpTile(it)); });
    grid.appendChild(tiles);
  }

  ["All"].concat(present).forEach(function (q, i) {
    var b = el("button", "filter-btn" + (i === 0 ? " active" : ""), q);
    if (q !== "All") b.style.setProperty("--accent", QUALITY_COLORS[q] || "#b2b2b2");
    b.addEventListener("click", function () {
      filterBar.querySelectorAll(".filter-btn").forEach(function (x) { x.classList.remove("active"); });
      b.classList.add("active");
      draw(q);
    });
    filterBar.appendChild(b);
  });

  draw("All");
}

function buildCount(shown, total) {
  return el("p", "bp-count-line", "Showing <strong>" + shown + "</strong> of " + total + " items.");
}

function bpTile(it) {
  var tag = it.market ? document.createElement("a") : document.createElement("div");
  tag.className = "bp-tile";
  tag.style.setProperty("--q", it.color);
  tag.title = it.name + (it.count > 1 ? " (x" + it.count + ")" : "");
  if (it.market) {
    tag.href = "https://steamcommunity.com/market/listings/440/" + encodeURIComponent(it.market);
    tag.target = "_blank";
    tag.rel = "noopener noreferrer";
  }
  if (it.icon) {
    var img = document.createElement("img");
    img.src = ICON_BASE + it.icon + "/96fx96f";
    img.alt = it.name;
    img.loading = "lazy";
    tag.appendChild(img);
  }
  if (it.count > 1) tag.appendChild(el("span", "bp-tile-count", "x" + it.count));
  tag.appendChild(el("span", "bp-tile-name", it.name));
  return tag;
}

/* ---------- Backpack Stats Dashboard ---------- */
async function renderStats() {
  const root = document.getElementById("stats-root");
  if (!root) return;
  if (typeof STEAM_WORKER_URL === "undefined" || !STEAM_WORKER_URL) {
    root.innerHTML = "<p class='empty'>Live stats need the Cloudflare Worker configured in js/config.js.</p>";
    return;
  }
  try {
    const res = await fetch(STEAM_WORKER_URL + "?steamid=" + encodeURIComponent(STEAM_ID), { cache: "no-store" });
    const data = await res.json();
    if (data.error) throw new Error(data.error);
    if (!data.descriptions || !data.assets) throw new Error("no inventory data");

    // map class -> {quality, type, name, color, icon, market}
    const byId = {};
    data.descriptions.forEach(function (d) {
      let quality = "Unique", type = "Other";
      (d.tags || []).forEach(function (t) {
        if (t.category === "Quality") quality = t.localized_tag_name;
        if (t.category === "Type") type = t.localized_tag_name;
      });
      byId[d.classid + "_" + d.instanceid] = {
        quality: quality, type: type,
        name: d.market_name || d.name,
        color: "#" + (d.name_color || "7d6d00"),
        icon: d.icon_url_large || d.icon_url,
        market: d.marketable ? d.market_hash_name : null
      };
    });

    const total = data.assets.length;
    const qCount = {}, tCount = {}, unusuals = [];
    data.assets.forEach(function (a) {
      const info = byId[a.classid + "_" + a.instanceid];
      if (!info) return;
      qCount[info.quality] = (qCount[info.quality] || 0) + 1;
      tCount[info.type] = (tCount[info.type] || 0) + 1;
    });
    Object.keys(byId).forEach(function (k) { if (byId[k].quality === "Unusual") unusuals.push(byId[k]); });

    root.innerHTML = "";

    // headline stat cards
    const big = el("div", "stat-cards");
    const cards = [
      ["Total items", total],
      ["Unique items", data.descriptions.length],
      ["Unusuals", qCount["Unusual"] || 0],
      ["Strange", qCount["Strange"] || 0],
      ["Genuine", qCount["Genuine"] || 0],
      ["Haunted", qCount["Haunted"] || 0]
    ];
    cards.forEach(function (c) {
      const card = el("div", "stat-card");
      card.appendChild(el("div", "stat-num", String(c[1])));
      card.appendChild(el("div", "stat-lbl", c[0]));
      big.appendChild(card);
    });
    root.appendChild(big);

    // quality breakdown bars
    root.appendChild(el("h2", "stats-h", "By quality"));
    root.appendChild(barChart(qCount, total, QUALITY_RANK, function (q) { return QUALITY_COLORS[q] || "#b2b2b2"; }));

    // type breakdown bars (top 8)
    root.appendChild(el("h2", "stats-h", "By type"));
    const topTypes = Object.keys(tCount).sort(function (a, b) { return tCount[b] - tCount[a]; }).slice(0, 8);
    root.appendChild(barChart(tCount, total, topTypes, function () { return "var(--orange)"; }));

    // rarest spotlight
    if (unusuals.length) {
      root.appendChild(el("h2", "stats-h", "Unusual spotlight"));
      const tiles = el("div", "bp-tiles");
      unusuals.forEach(function (it) { tiles.appendChild(bpTile(it)); });
      root.appendChild(tiles);
    }

    loadBackpackValue(root);
  } catch (e) {
    root.innerHTML = "<p class='empty err'>Couldn't load stats (" + e.message + "). Is the inventory public and the Worker up?</p>";
  }
}

function loadBackpackValue(root) {
  fetch(STEAM_WORKER_URL + "?value=1&steamid=" + encodeURIComponent(STEAM_ID), { cache: "no-store" })
    .then(function (r) { return r.json(); })
    .then(function (v) {
      if (!v || v.error || v.refined == null) return;
      const keys = v.keysRate ? Math.round(v.refined / v.keysRate) : null;
      const usd = v.usdPerRef ? v.refined * v.usdPerRef : null;
      const banner = el("div", "value-banner");
      banner.appendChild(el("div", "value-lbl", "Estimated backpack value"));
      const main = el("div", "value-main");
      if (keys != null) main.appendChild(el("span", "value-keys", keys.toLocaleString() + " keys"));
      if (usd != null) main.appendChild(el("span", "value-usd", "≈ $" + usd.toLocaleString(undefined, { maximumFractionDigits: 0 })));
      banner.appendChild(main);
      let sub = "≈ " + Math.round(v.refined).toLocaleString() + " refined";
      if (v.updated) sub += " · via backpack.tf, updated " + new Date(v.updated * 1000).toLocaleDateString();
      banner.appendChild(el("div", "value-sub", sub));
      root.insertBefore(banner, root.firstChild);
    })
    .catch(function () {});
}

function barChart(counts, total, order, colorFn) {
  const wrap = el("div", "bar-chart");
  const max = Math.max.apply(null, order.map(function (k) { return counts[k] || 0; }).concat([1]));
  order.forEach(function (k) {
    const n = counts[k] || 0;
    if (!n) return;
    const row = el("div", "bar-row");
    row.appendChild(el("span", "bar-label", k));
    const track = el("div", "bar-track");
    const fill = el("div", "bar-fill");
    fill.style.width = Math.max(2, (n / max) * 100) + "%";
    fill.style.background = colorFn(k);
    track.appendChild(fill);
    row.appendChild(track);
    row.appendChild(el("span", "bar-val", n + " (" + ((n / total) * 100).toFixed(1) + "%)"));
    wrap.appendChild(row);
  });
  return wrap;
}

/* ---------- Hat Battles ---------- */
function sbHeaders() {
  return { apikey: SUPABASE_ANON_KEY, Authorization: "Bearer " + SUPABASE_ANON_KEY, "Content-Type": "application/json" };
}

async function renderBattles() {
  const arena = document.getElementById("battle-arena");
  const board = document.getElementById("battle-board");
  if (!arena) return;
  if (typeof STEAM_WORKER_URL === "undefined" || !STEAM_WORKER_URL) {
    arena.innerHTML = "<p class='empty'>Needs the Worker configured.</p>"; return;
  }
  let pool = [];
  try {
    const res = await fetch(STEAM_WORKER_URL + "?steamid=" + encodeURIComponent(STEAM_ID), { cache: "no-store" });
    const inv = await res.json();
    if (!inv.descriptions) throw new Error("no inventory");
    const seen = {};
    inv.descriptions.forEach(function (d) {
      let type = "", quality = "Unique";
      (d.tags || []).forEach(function (t) {
        if (t.category === "Type") type = t.localized_tag_name;
        if (t.category === "Quality") quality = t.localized_tag_name;
      });
      if (type !== "Cosmetic") return;
      const name = d.market_name || d.name;
      if (seen[name]) return; seen[name] = 1;
      pool.push({ name: name, icon: d.icon_url_large || d.icon_url, quality: quality });
    });
    if (pool.length < 2) throw new Error("not enough cosmetics");
    // Cap to the most interesting hats (rarest first) so matchups repeat and
    // the leaderboard actually fills up.
    const qrank = function (q) { var i = QUALITY_RANK.indexOf(q); return i < 0 ? 99 : i; };
    pool.sort(function (a, b) { return qrank(a.quality) - qrank(b.quality); });
    pool = pool.slice(0, 50);
  } catch (e) {
    arena.innerHTML = "<p class='empty err'>Couldn't load hats (" + e.message + ").</p>"; return;
  }

  function twoHats() {
    const a = Math.floor(Math.random() * pool.length);
    let b = Math.floor(Math.random() * pool.length);
    while (b === a) b = Math.floor(Math.random() * pool.length);
    return [pool[a], pool[b]];
  }

  function hatCard(h, onPick) {
    const c = el("div", "battle-card");
    if (h.icon) { const img = document.createElement("img"); img.src = ICON_BASE + h.icon + "/120fx120f"; img.alt = h.name; c.appendChild(img); }
    c.appendChild(el("div", "battle-name", h.name));
    c.addEventListener("click", function () { onPick(); });
    return c;
  }

  async function vote(winner, loser) {
    try {
      await fetch(SUPABASE_URL + "/rest/v1/rpc/vote_hat", {
        method: "POST", headers: sbHeaders(), body: JSON.stringify({ w: winner, l: loser })
      });
    } catch (e) {}
  }

  async function loadBoard() {
    if (!board) return;
    try {
      const res = await fetch(SUPABASE_URL + "/rest/v1/hat_stats?select=name,wins,battles&order=wins.desc&limit=200", { headers: sbHeaders() });
      if (!res.ok) return;
      let rows = await res.json();
      rows = rows.filter(function (r) { return r.battles >= 1; })
        .map(function (r) { r.rate = r.wins / r.battles; return r; })
        .sort(function (a, b) { return b.rate - a.rate || b.battles - a.battles; })
        .slice(0, 10);
      board.innerHTML = "<h2 class='stats-h'>Top hats</h2>";
      if (!rows.length) { board.appendChild(el("p", "muted", "Not enough votes yet — keep battling!")); return; }
      const ol = el("ol", "battle-rank");
      rows.forEach(function (r) {
        const li = el("li");
        li.innerHTML = "<span class='rank-name'>" + r.name + "</span><span class='rank-rate'>" +
          Math.round(r.rate * 100) + "% (" + r.wins + "/" + r.battles + ")</span>";
        ol.appendChild(li);
      });
      board.appendChild(ol);
    } catch (e) {}
  }

  function round() {
    const pair = twoHats();
    arena.innerHTML = "";
    const wrap = el("div", "battle-pair");
    wrap.appendChild(hatCard(pair[0], function () { vote(pair[0].name, pair[1].name).then(loadBoard); round(); }));
    wrap.appendChild(el("div", "battle-vs", "VS"));
    wrap.appendChild(hatCard(pair[1], function () { vote(pair[1].name, pair[0].name).then(loadBoard); round(); }));
    arena.appendChild(wrap);
  }

  round();
  loadBoard();
}

/* ---------- Pixel Canvas ---------- */
function renderCanvas() {
  const gridEl = document.getElementById("pixel-grid");
  const paletteEl = document.getElementById("palette");
  const statusEl = document.getElementById("canvas-status");
  if (!gridEl) return;
  const SIZE = 40;
  const COLORS = ["#2a2622", "#ffffff", "#b8383b", "#cf7336", "#e0b341", "#6e9b3a",
    "#4a8c8c", "#5885a2", "#8650ac", "#d32ce6", "#7a5a3a", "#b0b0b0"];
  let current = COLORS[2];

  const configured = (typeof SUPABASE_URL !== "undefined" && SUPABASE_URL && SUPABASE_URL.indexOf("http") === 0 && SUPABASE_URL.indexOf("PASTE") < 0);

  // palette
  COLORS.forEach(function (col, i) {
    const sw = document.createElement("button");
    sw.className = "swatch" + (i === 2 ? " active" : "");
    sw.style.background = col;
    sw.addEventListener("click", function () {
      current = col;
      paletteEl.querySelectorAll(".swatch").forEach(function (x) { x.classList.remove("active"); });
      sw.classList.add("active");
    });
    paletteEl.appendChild(sw);
  });

  // grid
  const cells = {};
  for (let y = 0; y < SIZE; y++) {
    for (let x = 0; x < SIZE; x++) {
      const c = document.createElement("div");
      c.className = "pixel";
      c.dataset.x = x; c.dataset.y = y;
      c.addEventListener("click", function () { place(x, y, c); });
      gridEl.appendChild(c);
      cells[x + "_" + y] = c;
    }
  }

  function paint(list) {
    list.forEach(function (p) {
      const c = cells[p.x + "_" + p.y];
      if (c) c.style.background = p.color;
    });
  }

  async function load() {
    if (!configured) return;
    try {
      const res = await fetch(SUPABASE_URL + "/rest/v1/pixels?select=x,y,color", { headers: sbHeaders() });
      if (res.ok) paint(await res.json());
    } catch (e) {}
  }

  async function place(x, y, cell) {
    cell.style.background = current; // optimistic
    if (!configured) { if (statusEl) statusEl.textContent = "Demo mode — set up Supabase to make it shared."; return; }
    const last = Number(localStorage.getItem("px_last") || 0);
    if (Date.now() - last < 500) return;
    localStorage.setItem("px_last", String(Date.now()));
    try {
      await fetch(SUPABASE_URL + "/rest/v1/pixels?on_conflict=x,y", {
        method: "POST",
        headers: Object.assign(sbHeaders(), { Prefer: "resolution=merge-duplicates,return=minimal" }),
        body: JSON.stringify({ x: x, y: y, color: current })
      });
    } catch (e) {}
  }

  load();
  if (configured) setInterval(load, 4000);
  else if (statusEl) statusEl.textContent = "Demo mode — pixels are local until Supabase tables are set up.";
}

/* ---------- Guess the Price ---------- */
async function renderGuess() {
  const root = document.getElementById("guess-game");
  if (!root) return;
  if (typeof STEAM_WORKER_URL === "undefined" || !STEAM_WORKER_URL) {
    root.innerHTML = "<p class='empty'>This game needs the Cloudflare Worker + backpack.tf key configured.</p>";
    return;
  }
  try {
    const [invRes, priceRes] = await Promise.all([
      fetch(STEAM_WORKER_URL + "?steamid=" + encodeURIComponent(STEAM_ID), { cache: "no-store" }),
      fetch(STEAM_WORKER_URL + "?prices=1&steamid=" + encodeURIComponent(STEAM_ID), { cache: "no-store" })
    ]);
    const inv = await invRes.json();
    const pd = await priceRes.json();
    if (pd.error) throw new Error(pd.error);
    if (!inv.descriptions || !pd.prices) throw new Error("missing data");
    const priceMap = pd.prices;
    const keysRate = pd.keysRate || 57;

    // build playable items: Unique (exact name) + Strange (strip prefix), with icon + price
    const seen = {};
    const pool = [];
    inv.descriptions.forEach(function (d) {
      let quality = "Unique";
      (d.tags || []).forEach(function (t) { if (t.category === "Quality") quality = t.localized_tag_name; });
      const mname = d.market_name || d.name;
      let base = null, ref = null;
      if (quality === "Unique" && priceMap[mname] && priceMap[mname].u != null) {
        base = mname; ref = priceMap[mname].u;
      } else if (quality === "Strange" && mname.indexOf("Strange ") === 0) {
        const b = mname.slice(8);
        if (priceMap[b] && priceMap[b].s != null) { base = b; ref = priceMap[b].s; }
      }
      if (base == null || ref == null || ref < 0.11) return;
      if (seen[mname]) return;
      seen[mname] = 1;
      pool.push({ name: mname, icon: d.icon_url_large || d.icon_url, ref: ref });
    });

    if (pool.length < 5) throw new Error("not enough priced items to play");

    let score = 0, rounds = 0;
    let best = 0; try { best = Number(localStorage.getItem("guess_best") || 0); } catch (e) {}

    function refToKeys(r) { return (r / keysRate); }
    function fmtVal(r) {
      const k = refToKeys(r);
      if (k >= 1) return k.toFixed(1) + " keys (" + r.toFixed(2) + " ref)";
      return r.toFixed(2) + " ref";
    }

    function round() {
      const item = pool[Math.floor(Math.random() * pool.length)];
      root.innerHTML = "";
      const scoreBar = el("div", "guess-score");
      scoreBar.innerHTML = "Score: <strong>" + score + "</strong> &nbsp;·&nbsp; Round " + (rounds + 1) +
        " &nbsp;·&nbsp; Best: " + best;
      root.appendChild(scoreBar);

      const card = el("div", "guess-card");
      if (item.icon) {
        const img = document.createElement("img");
        img.src = ICON_BASE + item.icon + "/120fx120f";
        img.alt = item.name; img.className = "guess-img";
        card.appendChild(img);
      }
      card.appendChild(el("div", "guess-name", item.name));
      card.appendChild(el("label", "guess-label", "Your guess (refined metal):"));
      const inputRow = el("div", "guess-input-row");
      const input = document.createElement("input");
      input.type = "number"; input.min = "0"; input.step = "0.01";
      input.className = "build-select guess-input"; input.placeholder = "e.g. 12.5";
      const go = el("button", "btn btn-primary", "Guess");
      inputRow.appendChild(input); inputRow.appendChild(go);
      card.appendChild(inputRow);
      const result = el("div", "guess-result");
      card.appendChild(result);
      root.appendChild(card);
      input.focus();

      function submit() {
        const guess = parseFloat(input.value);
        if (isNaN(guess) || guess < 0) { input.focus(); return; }
        go.disabled = true; input.disabled = true;
        const off = Math.abs(guess - item.ref) / item.ref;
        const pts = Math.max(0, Math.round(100 * (1 - Math.min(1, off))));
        score += pts; rounds++;
        if (score > best) { best = score; try { localStorage.setItem("guess_best", String(best)); } catch (e) {} }
        const verdict = pts >= 90 ? "Nailed it!" : pts >= 60 ? "Close!" : pts >= 30 ? "Not quite." : "Way off.";
        result.innerHTML =
          "<div class='guess-verdict'>" + verdict + " <strong>+" + pts + "</strong></div>" +
          "<div class='guess-actual'>Actual: <strong>" + fmtVal(item.ref) + "</strong> &nbsp;·&nbsp; you guessed " + guess.toFixed(2) + " ref</div>";
        const next = el("button", "btn btn-ghost guess-next", "Next item →");
        next.addEventListener("click", round);
        result.appendChild(next);
        next.focus();
      }
      go.addEventListener("click", submit);
      input.addEventListener("keydown", function (e) { if (e.key === "Enter") submit(); });
    }

    root.innerHTML = "";
    round();
  } catch (e) {
    root.innerHTML = "<p class='empty err'>Couldn't start the game (" + e.message + "). Needs the Worker's prices route + a public inventory.</p>";
  }
}

/* ---------- Loadout Builder ---------- */
function renderBuilder() {
  const controls = document.getElementById("builder-controls");
  const preview = document.getElementById("builder-preview");
  const shareBox = document.getElementById("builder-share");
  if (!controls || !preview) return;

  const classes = Object.keys(WEAPONS);
  const params = new URLSearchParams(location.search);
  const state = {
    cls: params.get("c") && WEAPONS[params.get("c")] ? params.get("c") : classes[0],
    p: params.get("p") || "",
    s: params.get("s") || "",
    m: params.get("m") || "",
    h: (params.get("h") || "").split("~").filter(Boolean),
    n: params.get("n") || ""
  };

  function opt(value, label, selected) {
    const o = document.createElement("option");
    o.value = value; o.textContent = label;
    if (selected) o.selected = true;
    return o;
  }

  function build() {
    controls.innerHTML = "";

    // class picker
    const clsRow = el("div", "build-field");
    clsRow.appendChild(el("label", "build-label", "Class"));
    const clsBtns = el("div", "class-filter build-classes");
    classes.forEach(function (c) {
      const b = el("button", "filter-btn " + classSlug(c) + (c === state.cls ? " active" : ""), c);
      b.style.setProperty("--accent", "var(--accent)");
      b.addEventListener("click", function () {
        if (state.cls === c) return;
        state.cls = c; state.p = ""; state.s = ""; state.m = "";
        build(); update();
      });
      clsBtns.appendChild(b);
    });
    clsRow.appendChild(clsBtns);
    controls.appendChild(clsRow);

    // weapon slot selects
    const w = WEAPONS[state.cls];
    [["p", "Primary", w.primary], ["s", "Secondary", w.secondary], ["m", "Melee", w.melee]].forEach(function (slot) {
      const key = slot[0], pool = slot[2];
      const field = el("div", "build-field");
      field.appendChild(el("label", "build-label", slot[1]));
      const sel = document.createElement("select");
      sel.className = "build-select";
      sel.appendChild(opt("", "— random / none —", !state[key]));
      pool.forEach(function (it) { sel.appendChild(opt(it, it, state[key] === it)); });
      sel.addEventListener("change", function () { state[key] = sel.value; update(); });
      field.appendChild(sel);
      controls.appendChild(field);
    });

    // cosmetics (two slots)
    [0, 1].forEach(function (i) {
      const field = el("div", "build-field");
      field.appendChild(el("label", "build-label", "Cosmetic " + (i + 1)));
      const sel = document.createElement("select");
      sel.className = "build-select";
      sel.appendChild(opt("", "— none —", !state.h[i]));
      COSMETICS.forEach(function (it) { sel.appendChild(opt(it, it, state.h[i] === it)); });
      sel.addEventListener("change", function () { state.h[i] = sel.value; update(); });
      field.appendChild(sel);
      controls.appendChild(field);
    });

    // name
    const nameField = el("div", "build-field");
    nameField.appendChild(el("label", "build-label", "Loadout name"));
    const nameInput = document.createElement("input");
    nameInput.className = "build-select"; nameInput.type = "text"; nameInput.maxLength = 40;
    nameInput.placeholder = "My Sick Loadout"; nameInput.value = state.n;
    nameInput.addEventListener("input", function () { state.n = nameInput.value; update(); });
    nameField.appendChild(nameInput);
    controls.appendChild(nameField);
  }

  function update() {
    const items = [state.p, state.s, state.m].concat(state.h).filter(Boolean);
    const lo = {
      name: state.n || ("Custom " + state.cls),
      class: state.cls,
      image: "",
      blurb: "Built in the loadout builder.",
      items: items,
      notes: ""
    };
    preview.innerHTML = "";
    preview.appendChild(loadoutCard(lo));
    drawShare();
  }

  function shareUrl() {
    const q = new URLSearchParams();
    q.set("c", state.cls);
    if (state.p) q.set("p", state.p);
    if (state.s) q.set("s", state.s);
    if (state.m) q.set("m", state.m);
    const hats = state.h.filter(Boolean);
    if (hats.length) q.set("h", hats.join("~"));
    if (state.n) q.set("n", state.n);
    return location.origin + location.pathname + "?" + q.toString();
  }

  function drawShare() {
    shareBox.innerHTML = "";
    const btn = el("button", "btn btn-primary", "🔗 Copy share link");
    const msg = el("span", "share-msg");
    btn.addEventListener("click", function () {
      const url = shareUrl();
      navigator.clipboard.writeText(url).then(
        function () { msg.textContent = "Copied!"; },
        function () { msg.textContent = url; }
      );
    });
    shareBox.appendChild(btn);
    shareBox.appendChild(msg);
  }

  build();
  update();
}

function renderCuratedBackpack(grid) {
  if (typeof BACKPACK === "undefined" || !BACKPACK.length) {
    grid.appendChild(el("p", "empty", "No items yet. Add some in js/funpools.js."));
    return;
  }
  BACKPACK.forEach(function (it) {
    const color = (QUALITY_COLORS[it.quality]) || "#b2b2b2";
    const card = el("div", "bp-card");
    card.style.setProperty("--q", color);
    card.appendChild(el("div", "bp-quality", it.quality || "Normal"));
    const a = document.createElement("a");
    a.className = "bp-name";
    a.href = wikiUrl(it.wiki || it.name);
    a.target = "_blank";
    a.rel = "noopener noreferrer";
    a.textContent = it.name;
    card.appendChild(a);
    if (it.effect) card.appendChild(el("div", "bp-effect", "✦ " + it.effect));
    if (it.value) card.appendChild(el("div", "bp-value", it.value));
    if (it.note) card.appendChild(el("div", "bp-note", it.note));
    grid.appendChild(card);
  });
}
