/* ============================================================
   Logic for the Fun tools: randomizer, crate sim, backpack.
   Relies on main.js (el, wikiUrl, itemChip, loadoutCard, classSlug)
   and funpools.js (WEAPONS, COSMETICS, CRATE_*, QUALITY_COLORS, BACKPACK).
   ============================================================ */

function pick(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}
function pickN(arr, n) {
  const copy = arr.slice();
  const out = [];
  while (out.length < n && copy.length) {
    out.push(copy.splice(Math.floor(Math.random() * copy.length), 1)[0]);
  }
  return out;
}

/* ---------- Loadout Randomizer ---------- */
const RANDOM_BLURBS = [
  "Generated by pure chaos.", "No thoughts, just this.", "The algorithm has spoken.",
  "Statistically, a war crime.", "Somebody's gotta run it.", "Peak performance, probably.",
  "Don't question the dice.", "Certified cursed."
];

function renderRandomizer() {
  const out = document.getElementById("randomizer-output");
  const btn = document.getElementById("reroll-btn");
  if (!out || !btn) return;

  function roll() {
    const cls = pick(Object.keys(WEAPONS));
    const w = WEAPONS[cls];
    const items = [pick(w.primary), pick(w.secondary), pick(w.melee)]
      .concat(pickN(COSMETICS, 2));
    const lo = {
      name: "Random " + cls,
      class: cls,
      image: "",
      blurb: pick(RANDOM_BLURBS),
      items: items,
      notes: "Hit Reroll for another disaster."
    };
    out.innerHTML = "";
    out.appendChild(loadoutCard(lo));
  }

  btn.addEventListener("click", roll);
  roll();
}

/* ---------- Crate Opening Simulator ---------- */
function rollGrade() {
  const total = CRATE_GRADES.reduce((s, g) => s + g.weight, 0);
  let r = Math.random() * total;
  for (const g of CRATE_GRADES) {
    if ((r -= g.weight) <= 0) return g;
  }
  return CRATE_GRADES[0];
}

function renderCrate() {
  const stage = document.getElementById("crate-stage");
  const btn = document.getElementById("open-btn");
  const result = document.getElementById("crate-result");
  const histEl = document.getElementById("crate-history");
  if (!stage || !btn) return;

  const history = [];
  let rolling = false;

  function open() {
    if (rolling) return;
    rolling = true;
    btn.disabled = true;
    result.className = "crate-result";
    stage.classList.add("shaking");

    // spin through random names, then settle
    let ticks = 0;
    const spin = setInterval(function () {
      result.innerHTML = "<span class='spin-name'>" + pick(CRATE_ITEMS) + "</span>";
      if (++ticks > 16) {
        clearInterval(spin);
        settle();
      }
    }, 60);

    function settle() {
      stage.classList.remove("shaking");
      const unusual = Math.random() < UNUSUAL_CHANCE;
      const grade = unusual ? { name: "★ Unusual ★", color: "#8650ac" } : rollGrade();
      const item = pick(CRATE_ITEMS);

      result.innerHTML = "";
      result.style.setProperty("--grade", grade.color);
      result.classList.add("revealed");
      if (unusual) result.classList.add("jackpot");

      const gradeTag = el("div", "grade-tag", grade.name);
      gradeTag.style.color = grade.color;
      const a = document.createElement("a");
      a.className = "crate-item-name";
      a.href = wikiUrl(item);
      a.target = "_blank";
      a.rel = "noopener noreferrer";
      a.textContent = item;
      a.style.color = grade.color;
      result.appendChild(gradeTag);
      result.appendChild(a);
      if (unusual) {
        result.appendChild(el("div", "unusual-effect", "Effect: " + pick(UNUSUAL_EFFECTS)));
      }

      history.unshift({ item: item, grade: grade.name, color: grade.color });
      drawHistory();
      rolling = false;
      btn.disabled = false;
    }
  }

  function drawHistory() {
    if (!histEl) return;
    histEl.innerHTML = "<h3>Recent unboxes</h3>";
    const ul = el("ul", "history-list");
    history.slice(0, 10).forEach(function (h) {
      const li = el("li");
      const dot = el("span", "history-dot");
      dot.style.background = h.color;
      li.appendChild(dot);
      li.appendChild(document.createTextNode(h.item + " — " + h.grade));
      ul.appendChild(li);
    });
    histEl.appendChild(ul);
  }

  btn.addEventListener("click", open);
}

/* ---------- Backpack Showcase ---------- */
function renderBackpack() {
  const grid = document.getElementById("backpack-grid");
  if (!grid) return;
  if (typeof BACKPACK === "undefined" || !BACKPACK.length) {
    grid.appendChild(el("p", "empty", "No items yet. Add some in js/funpools.js."));
    return;
  }
  BACKPACK.forEach(function (it) {
    const color = (QUALITY_COLORS[it.quality]) || "#b2b2b2";
    const card = el("div", "bp-card");
    card.style.setProperty("--q", color);
    card.appendChild(el("div", "bp-quality", it.quality || "Normal"));
    const a = document.createElement("a");
    a.className = "bp-name";
    a.href = wikiUrl(it.wiki || it.name);
    a.target = "_blank";
    a.rel = "noopener noreferrer";
    a.textContent = it.name;
    card.appendChild(a);
    if (it.effect) card.appendChild(el("div", "bp-effect", "✦ " + it.effect));
    if (it.value) card.appendChild(el("div", "bp-value", it.value));
    if (it.note) card.appendChild(el("div", "bp-note", it.note));
    grid.appendChild(card);
  });
}
